export const categories = [
  {
    id: "stay",
    name: "Stay",
    desc: "PGs, rooms & flatmates",
    color: "green",
  },
  {
    id: "eat",
    name: "Eat",
    desc: "Tiffin & home chefs",
    color: "pink",
  },
  {
    id: "live",
    name: "Live",
    desc: "Laundry & home help",
    color: "cyan",
  },
  {
    id: "move",
    name: "Move",
    desc: "Movers & storage",
    color: "orange",
  },
  {
    id: "go",
    name: "Go",
    desc: "Parking & rentals",
    color: "purple",
  },
];

export const listings = [
  {
    id: "premium-student-pg",
    title: "Premium Student PG",
    category: "stay",
    location: "Sector 62, Noida",
    price: "₹8,500",
    rating: 4.9,
    reviews: 128,
    image: "/images/listing-pg.jpg",
    tags: ["WiFi", "Food", "AC"],
  },
  {
    id: "homemade-tiffin",
    title: "Homemade Tiffin",
    category: "eat",
    location: "Sector 61, Noida",
    price: "₹2,999",
    rating: 4.8,
    reviews: 96,
    image: "/images/listing-tiffin.jpg",
    tags: ["Veg", "Delivery", "Healthy"],
  },
  {
    id: "fully-furnished-room",
    title: "Fully Furnished Room",
    category: "stay",
    location: "Sector 137, Noida",
    price: "₹11,000",
    rating: 4.7,
    reviews: 82,
    image: "/images/listing-room.jpg",
    tags: ["Furnished", "WiFi", "AC"],
  },
  {
    id: "student-laundry",
    title: "Student Laundry Service",
    category: "live",
    location: "Sector 62, Noida",
    price: "₹499",
    rating: 4.8,
    reviews: 64,
    image: "/images/listing-laundry.jpg",
    tags: ["Pickup", "Delivery"],
  },
  {
    id: "local-movers",
    title: "Local Movers",
    category: "move",
    location: "Noida",
    price: "₹1,499",
    rating: 4.7,
    reviews: 51,
    image: "/images/listing-movers.jpg",
    tags: ["Moving", "Packing"],
  },
];

export const orders = [
  {
    id: "ORD-001",
    customer: "Student User",
    service: "Premium Student PG",
    amount: "₹8,500",
    status: "Confirmed",
  },
  {
    id: "ORD-002",
    customer: "Student User",
    service: "Homemade Tiffin",
    amount: "₹2,999",
    status: "Pending",
  },
];
